apiVersion: v1
kind: Service
metadata:
  name: tado-exporter
  labels:
    app: tado-exporter
spec:
  type: LoadBalancer
  ports:
    - name: metrics
      protocol: TCP
      port: 9898
      targetPort: 9898
  selector:
    app: tado-exporter
