apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: tado-servicemonitor
  name: tado-servicemonitor
  #namespace: mon
spec:
  endpoints:
    - port: metrics
      path: /
  namespaceSelector:
    matchNames:
    - tado
  selector:
    matchLabels:
      app: tado-exporter
